# 调试模式
debug: false
# 端口
port: 23333

# 每秒全局限制次数
global_limit: 4
# 每秒全局突发次数
global_burst: 8
# 每秒限制次数
ip_limit: 2
# 每秒突发次数
ip_burst: 4

# accessKey 缓存（天）
accesskey_max_cache_time: 7
# 播放链接缓存（分钟）
playurl_cache_time: 60

# 代理(留空禁用)
proxy_cn: socks5://127.0.0.1:7891
proxy_hk: socks5://127.0.0.1:7891
proxy_tw: socks5://127.0.0.1:7891
proxy_th: socks5://127.0.0.1:7891

# 反代(留空禁用)
reverse_cn: api.bilibili.com
reverse_hk: api.bilibili.com
reverse_tw: api.bilibili.com
reverse_th: api.bilibili.com