# 调试模式
debug: false
# 端口
port: 23333

# 每秒限制次数
ip_limit: 2
# 每秒突发次数
ip_burst: 4

# accessKey 缓存（天）
accesskey_cache_time: 7
# 用户资料缓存（天）
users_cache_time: 7
# 播放链接缓存（分钟）
playurl_cache_time: 15
# 东南亚 season api 缓存（分钟）
th_season_cache_time: 15
# 东南亚 字幕 api 缓存（分钟）
th_subtitle_cache_time: 15

# 代理(留空禁用)
proxy_cn: socks5://127.0.0.1:7891
proxy_hk: socks5://127.0.0.1:7891
proxy_tw: socks5://127.0.0.1:7891
proxy_th: socks5://127.0.0.1:7891

# 反代(留空禁用)
reverse_cn: api.bilibili.com
reverse_hk: api.bilibili.com
reverse_tw: api.bilibili.com
reverse_th: api.bilibili.com

# 鉴权+缓存
auth_cn: true
auth_hk: true
auth_tw: true
auth_th: true

# Postgres 数据库
pg_host: test-postgres
pg_user: postgres
pg_password: test-password
pg_dbname: postgres
pg_port: 5432